import React, { useState, useEffect, useRef, useCallback } from 'react';
import { useClient } from '../context/ClientContext';
import { useAuth } from '../context/AuthContext';
import { updateCreditBalance, addCreditHistoryEntry } from '../api/hoaDuesService';
import { translateToSpanish } from '../api/translate';
import { isSuperAdmin, isAdmin } from '../utils/userRoles';
import { getMexicoDateString } from '../utils/timezone';
import { dateOnlyInputToMexicoISO } from '../utils/dateUtils';
import { formatAsMXN } from '../utils/hoaDuesUtils';
import { getFiscalYear } from '../utils/fiscalYearUtils';
import { getMexicoDate } from '../utils/timezone';
import { useDesktopStrings } from '../hooks/useDesktopStrings';
import { getAutogeneratedUserMessage, getAutogeneratedUserMessageEs, deriveSpanishCompanionForEnglishInput } from '@shared/utils/creditUserMessage.js';
import { ALLOWED_CREDIT_SOURCES } from '@shared/utils/creditSources.js';
import { handleDecimalAmountChange, parseDecimalInput } from '../utils/decimalAmountInput.js';
import '../styles/SandylandModalTheme.css';
import '../styles/CreditBalanceModals.css';

function inferCreditEntryType({ isAmountMode, mode, difference }) {
  if (isAmountMode) {
    return mode === 'add' ? 'credit_added' : 'credit_used';
  }
  return difference >= 0 ? 'credit_added' : 'credit_used';
}

function CreditBalanceEditModal({ isOpen, onClose, unitId, currentBalance, year, onUpdate, mode }) {
  const { selectedClient } = useClient();
  const { samsUser } = useAuth();
  const { t } = useDesktopStrings();
  
  // mode can be 'add', 'remove', or undefined (for edit/new balance mode)
  const isAmountMode = mode === 'add' || mode === 'remove';
  
  const [newBalance, setNewBalance] = useState('');
  const [amount, setAmount] = useState(''); // For add/remove mode
  const [entryDate, setEntryDate] = useState(getMexicoDateString());
  const [notes, setNotes] = useState('');
  const [userMessage, setUserMessage] = useState('');
  const [userMessageEs, setUserMessageEs] = useState('');
  const [source, setSource] = useState('admin');
  const [loading, setLoading] = useState(false);
  const [isTranslating, setIsTranslating] = useState(false);
  const [error, setError] = useState(null);
  const userMessageTouchedRef = useRef(false);
  const userMessageEsTouchedRef = useRef(false);
  const prevPreviewRef = useRef({ source: 'admin', type: 'credit_added' });

  // Check if user has permission to edit credit balance
  const canEdit = isSuperAdmin(samsUser) || isAdmin(samsUser, selectedClient?.id);

  // Initialize form when modal opens
  useEffect(() => {
    if (isOpen) {
      if (isAmountMode) {
        // Amount mode: clear amount, set balance to current
        setAmount('');
        setNewBalance(currentBalance?.toString() || '0');
      } else {
        // Balance mode: set new balance to current balance initially
        setNewBalance(currentBalance?.toString() || '0');
        setAmount('');
      }
      setEntryDate(getMexicoDateString());
      setNotes('');
      setUserMessage(getAutogeneratedUserMessage({ source: 'admin', type: 'credit_added' }));
      setUserMessageEs(getAutogeneratedUserMessageEs({ source: 'admin', type: 'credit_added' }));
      setSource('admin');
      userMessageTouchedRef.current = false;
      userMessageEsTouchedRef.current = false;
      prevPreviewRef.current = { source: 'admin', type: 'credit_added' };
      setError(null);
    }
  }, [isOpen, currentBalance, isAmountMode]);

  const amountValueForPreview = parseDecimalInput(amount) || 0;
  const currentBalanceValueForPreview = parseFloat(currentBalance) || 0;
  const previewDifference = isAmountMode
    ? (mode === 'add' ? amountValueForPreview : -amountValueForPreview)
    : (parseFloat(newBalance) || currentBalanceValueForPreview) - currentBalanceValueForPreview;
  const previewSource = isAmountMode ? source : 'admin';
  const previewType = inferCreditEntryType({
    isAmountMode,
    mode,
    difference: previewDifference
  });

  useEffect(() => {
    if (!isOpen) {
      return;
    }

    const { source: prevSource, type: prevType } = prevPreviewRef.current;
    const autoEnForPrev = getAutogeneratedUserMessage({ source: prevSource, type: prevType });
    const autoEsForPrev = getAutogeneratedUserMessageEs({ source: prevSource, type: prevType });

    if (!userMessageTouchedRef.current) {
      setUserMessage(getAutogeneratedUserMessage({ source: previewSource, type: previewType }));
    } else {
      setUserMessage((prev) => (
        prev.trim() === autoEnForPrev.trim()
          ? getAutogeneratedUserMessage({ source: previewSource, type: previewType })
          : prev
      ));
    }

    if (!userMessageEsTouchedRef.current) {
      setUserMessageEs(getAutogeneratedUserMessageEs({ source: previewSource, type: previewType }));
    } else {
      setUserMessageEs((prev) => (
        prev.trim() === autoEsForPrev.trim()
          ? getAutogeneratedUserMessageEs({ source: previewSource, type: previewType })
          : prev
      ));
    }

    prevPreviewRef.current = { source: previewSource, type: previewType };
  }, [isOpen, previewSource, previewType]);

  const handleTranslate = useCallback(async () => {
    if (!userMessage.trim()) {
      return;
    }
    setIsTranslating(true);
    try {
      if (!userMessageEs.trim()) {
        const result = await translateToSpanish(userMessage.trim());
        if (result.success) {
          userMessageEsTouchedRef.current = true;
          setUserMessageEs(result.translatedText);
        }
      }
    } finally {
      setIsTranslating(false);
    }
  }, [userMessage, userMessageEs]);

  const handleSave = async () => {
    if (!canEdit) {
      setError(t('creditEdit.errorNoPermission'));
      return;
    }

    let newBalanceValue;
    
    if (isAmountMode) {
      // Amount mode: validate amount and calculate new balance
      // Ensure we're reading the latest amount value and trimming whitespace
      const amountStr = amount ? amount.toString().trim() : '';
      const amountValue = parseDecimalInput(amountStr);
      
      if (!amountStr || isNaN(amountValue) || amountValue === 0) {
        setError(t('creditEdit.errorNonZeroAmount'));
        return;
      }
      
      // Ensure currentBalance is parsed as a number
      const currentBalanceValue = parseFloat(currentBalance) || 0;
      
      if (mode === 'add') {
        newBalanceValue = currentBalanceValue + amountValue;
      } else { // mode === 'remove'
        newBalanceValue = currentBalanceValue - amountValue;
      }
    } else {
      // Balance mode: validate new balance
      newBalanceValue = parseDecimalInput(newBalance);
      if (isNaN(newBalanceValue)) {
        setError(t('creditEdit.errorValidBalance'));
        return;
      }

      const currentBalanceValue = currentBalance || 0;
      const difference = newBalanceValue - currentBalanceValue;

      // Check if there's actually a change
      if (Math.abs(difference) < 0.01) {
        setError(t('creditEdit.errorDifferentBalance'));
        return;
      }
    }

    if (!notes.trim()) {
      setError(t('creditEdit.errorExplainChange'));
      return;
    }

    if (!userMessage.trim()) {
      setError(t('creditEdit.errorUserMessage'));
      return;
    }

    if (!entryDate) {
      setError(t('creditEdit.errorSelectDate'));
      return;
    }

    if (isAmountMode && !source.trim()) {
      setError(t('creditEntry.errorProvideSource'));
      return;
    }

    setLoading(true);
    setError(null);

    try {
      // Use fiscal year as fallback if year prop is not provided
      let yearToUse = year;
      if (!yearToUse) {
        const fiscalYearStartMonth = selectedClient?.configuration?.fiscalYearStartMonth || 1;
        yearToUse = getFiscalYear(getMexicoDate(), fiscalYearStartMonth);
      }
      
      const dateISO = dateOnlyInputToMexicoISO(entryDate);
      
      if (isAmountMode) {
        // For Add/Remove: Use direct history entry API with the amount
        const amountValue = parseDecimalInput(amount);
        // For remove mode, make amount negative
        const amountToAdd = mode === 'remove' ? -amountValue : amountValue;
        
        await addCreditHistoryEntry(
          selectedClient.id,
          unitId,
          amountToAdd, // Positive for add, negative for remove
          dateISO,
          notes.trim(),
          source.trim(),
          userMessage.trim(),
          userMessageEs.trim()
        );
      } else {
        // For Edit Balance: Use updateCreditBalance API with new balance
        await updateCreditBalance(
          selectedClient.id,
          unitId,
          yearToUse,
          newBalanceValue,
          notes.trim(),
          dateISO,
          userMessage.trim(),
          userMessageEs.trim()
        );
      }

      // Call the parent's update callback if provided (this will refresh the data)
      if (onUpdate) {
        await onUpdate();
      }

      onClose();
    } catch (err) {
      console.error('Error updating credit balance:', err);
      setError(err.message || t('creditEdit.errorUpdateFailed'));
    } finally {
      setLoading(false);
    }
  };

  const handleCancel = () => {
    setNewBalance('');
    setAmount('');
    setEntryDate(getMexicoDateString());
    setNotes('');
    setUserMessage('');
    setUserMessageEs('');
    setSource('admin');
    userMessageTouchedRef.current = false;
    userMessageEsTouchedRef.current = false;
    setError(null);
    onClose();
  };

  // Calculate preview values based on mode
  let newBalanceValue, difference, isAdd, isRemove;
  
  if (isAmountMode) {
    const amountValue = parseDecimalInput(amount) || 0;
    const currentBalanceValue = currentBalance || 0;
    if (mode === 'add') {
      newBalanceValue = currentBalanceValue + amountValue;
      difference = amountValue;
      isAdd = true;
      isRemove = false;
    } else { // mode === 'remove'
      newBalanceValue = currentBalanceValue - amountValue;
      difference = -amountValue;
      isAdd = false;
      isRemove = true;
    }
  } else {
    newBalanceValue = parseDecimalInput(newBalance) || currentBalance || 0;
    const currentBalanceValue = currentBalance || 0;
    difference = newBalanceValue - currentBalanceValue;
    isAdd = difference > 0;
    isRemove = difference < 0;
  }

  if (!isOpen) {
    return null;
  }

  if (!canEdit) {
    return (
      <div className="sandyland-modal-overlay" onClick={onClose}>
        <div className="sandyland-modal credit-balance-modal" onClick={(e) => e.stopPropagation()}>
          <div className="sandyland-modal-header credit-balance-modal-header">
            <h2 className="sandyland-modal-title credit-balance-modal-title">{t('creditEdit.accessDenied')}</h2>
            <button type="button" className="credit-modal-close" onClick={onClose} aria-label={t('creditHistory.close')}>×</button>
          </div>
          <div className="sandyland-modal-content credit-balance-modal-content">
            <p>{t('creditEdit.noPermission')}</p>
            <p>{t('creditEdit.adminOnly')}</p>
          </div>
          <div className="sandyland-modal-buttons">
            <button type="button" className="sandyland-btn sandyland-btn-secondary" onClick={onClose}>
              {t('creditHistory.close')}
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="sandyland-modal-overlay" onClick={handleCancel}>
      <div className="sandyland-modal credit-balance-modal" onClick={(e) => e.stopPropagation()}>
        <div className={`sandyland-modal-header credit-balance-modal-header ${isAdd ? 'header-add' : isRemove ? 'header-remove' : ''}`}>
          <h2 className="sandyland-modal-title credit-balance-modal-title">
            {mode === 'add'
              ? `➕ ${t('creditEdit.title.add', { unitId })}`
              : mode === 'remove'
                ? `➖ ${t('creditEdit.title.remove', { unitId })}`
                : t('creditEdit.title.edit', { unitId })}
          </h2>
          <button type="button" className="credit-modal-close" onClick={handleCancel} aria-label={t('creditEdit.cancel')}>×</button>
        </div>
        
        <div className="sandyland-modal-content credit-balance-modal-content">
          {error && (
            <div className="credit-balance-error" role="alert">
              {error}
            </div>
          )}
          
          <div className="credit-balance-form-group">
            <label htmlFor="currentBalance">{t('creditEdit.currentBalance')}</label>
            <div className="credit-balance-current-value" id="currentBalance">
              {formatAsMXN(currentBalance || 0)}
            </div>
          </div>

          <div className="credit-balance-form-group">
            <label htmlFor="entryDate">{t('creditEdit.entryDateRequired')}</label>
            <input
              type="date"
              id="entryDate"
              value={entryDate}
              onChange={(e) => setEntryDate(e.target.value)}
              disabled={loading}
              required
            />
            <div className="credit-balance-form-hint">
              {t('creditEdit.entryDateHint')}
            </div>
          </div>

          {isAmountMode ? (
            <>
              <div className="credit-balance-form-group">
                <label htmlFor="amount">
                  {mode === 'add' ? t('creditEdit.amountAddRequired') : t('creditEdit.amountRemoveRequired')}
                </label>
                <input
                  type="text"
                  inputMode="decimal"
                  id="amount"
                  className="credit-balance-amount-input"
                  value={amount}
                  onChange={(e) => handleDecimalAmountChange(e, setAmount)}
                  placeholder={mode === 'add' ? t('creditEdit.amountAddPlaceholder') : t('creditEdit.amountRemovePlaceholder')}
                  disabled={loading}
                  required
                  autoComplete="off"
                />
                <div className="credit-balance-form-hint">
                  {mode === 'add' 
                    ? t('creditEdit.amountAddHint')
                    : t('creditEdit.amountRemoveHint')}
                </div>
              </div>

              {amount && parseDecimalInput(amount) > 0 && (
                <div className={`credit-balance-preview ${isAdd ? 'preview-add' : 'preview-remove'}`}>
                  <div className="credit-balance-preview-label">{t('creditEdit.previewCurrent')}</div>
                  <div className="credit-balance-preview-amount">
                    {formatAsMXN(currentBalance || 0)}
                  </div>
                  <div className="credit-balance-preview-label">{t('creditEdit.previewChange')}</div>
                  <div className="credit-balance-preview-change">
                    {isAdd ? '+' : ''}{formatAsMXN(difference)}
                  </div>
                  <div className="credit-balance-preview-label">{t('creditEdit.previewNew')}</div>
                  <div className="credit-balance-preview-amount">
                    {formatAsMXN(newBalanceValue)}
                  </div>
                </div>
              )}

              <div className="credit-balance-form-group">
                <label htmlFor="source">{t('creditEntry.sourceRequired')}</label>
                <select
                  id="source"
                  value={source}
                  onChange={(e) => setSource(e.target.value)}
                  disabled={loading}
                  required
                >
                  {ALLOWED_CREDIT_SOURCES.map((src) => (
                    <option key={src} value={src}>{src}</option>
                  ))}
                </select>
              </div>
            </>
          ) : (
            <>
              <div className="credit-balance-form-group">
                <label htmlFor="newBalance">{t('creditEdit.newBalanceRequired')}</label>
                <input
                  type="text"
                  inputMode="decimal"
                  id="newBalance"
                  className="credit-balance-amount-input"
                  value={newBalance}
                  onChange={(e) => handleDecimalAmountChange(e, setNewBalance, { allowNegative: true })}
                  placeholder={t('creditEdit.newBalancePlaceholder')}
                  disabled={loading}
                  required
                  autoComplete="off"
                />
                <div className="credit-balance-form-hint">
                  {t('creditEdit.newBalanceHint')}
                </div>
              </div>

              {Math.abs(difference) > 0.01 && (
                <div className={`credit-balance-preview ${isAdd ? 'preview-add' : 'preview-remove'}`}>
                  <div className="credit-balance-preview-label">{t('creditEdit.previewChange')}</div>
                  <div className="credit-balance-preview-change">
                    {isAdd ? '+' : ''}{formatAsMXN(difference)}
                  </div>
                  <div className="credit-balance-preview-label">{t('creditEdit.previewNew')}</div>
                  <div className="credit-balance-preview-amount">
                    {formatAsMXN(newBalanceValue)}
                  </div>
                </div>
              )}
            </>
          )}

          <div className="credit-balance-field-pair">
            <div className="credit-balance-form-group">
              <label htmlFor="notes">{t('creditEdit.notesRequired')}</label>
              <textarea
                id="notes"
                value={notes}
                onChange={(e) => setNotes(e.target.value)}
                placeholder={t('creditEdit.notesPlaceholder')}
                rows="3"
                disabled={loading}
                required
              />
              <div className="credit-balance-form-hint">
                {t('creditEdit.notesAuditHint')}
              </div>
            </div>

            <div className="credit-balance-form-group">
              <label htmlFor="userMessage">{t('creditEdit.userMessageRequired')}</label>
              <textarea
                id="userMessage"
                value={userMessage}
                onChange={(e) => {
                  userMessageTouchedRef.current = true;
                  const nextEn = e.target.value;
                  setUserMessage(nextEn);
                  if (!userMessageEsTouchedRef.current) {
                    setUserMessageEs(deriveSpanishCompanionForEnglishInput(nextEn));
                  }
                }}
                placeholder={t('creditEdit.userMessagePlaceholder')}
                rows="2"
                disabled={loading}
                required
              />
              <div className="credit-balance-form-hint">
                {t('creditEdit.userMessageHint')}
              </div>
            </div>
          </div>

          <div className="credit-balance-form-group">
            <label htmlFor="userMessageEs">{t('creditEdit.userMessageEsLabel')}</label>
            <textarea
              id="userMessageEs"
              value={userMessageEs}
              onChange={(e) => {
                userMessageEsTouchedRef.current = true;
                setUserMessageEs(e.target.value);
              }}
              placeholder={t('creditEdit.userMessageEsPlaceholder')}
              rows="2"
              disabled={loading}
            />
            <div className="credit-balance-form-hint">
              {t('creditEdit.userMessageEsHint')}
            </div>
          </div>

          <div className="credit-balance-form-group">
            <button
              type="button"
              className="sandyland-btn sandyland-btn-secondary"
              onClick={handleTranslate}
              disabled={loading || isTranslating || !userMessage.trim()}
            >
              {isTranslating ? t('creditEdit.translating') : t('creditEdit.translateToSpanish')}
            </button>
          </div>

          {!isAmountMode && (
            <div className="credit-balance-form-hint">
              {t('creditEdit.adminSourceHint')}
            </div>
          )}

          <div className="credit-balance-form-note">
            <strong>{t('creditEdit.noteTitle')}</strong> {t('creditEdit.noteBody')}
          </div>
        </div>

        <div className="sandyland-modal-buttons">
          <button 
            type="button"
            className="sandyland-btn sandyland-btn-secondary" 
            onClick={handleCancel}
            disabled={loading}
          >
            {t('creditEdit.cancel')}
          </button>
          <button 
            type="button"
            className={`sandyland-btn sandyland-btn-primary ${isAdd ? 'sandyland-btn-success' : isRemove ? 'sandyland-btn-danger' : ''}`}
            onClick={handleSave}
            disabled={
              loading || 
              !notes.trim() ||
              !userMessage.trim() ||
              !entryDate || 
              (isAmountMode ? (!amount || parseDecimalInput(amount) <= 0) : (!newBalance || Math.abs(difference) < 0.01))
            }
          >
            {loading 
              ? t('creditEdit.saving')
              : mode === 'add' 
                ? t('creditHistory.addCredit')
                : mode === 'remove' 
                  ? t('creditHistory.removeCredit')
                  : t('creditEdit.saveChanges')}
          </button>
        </div>
      </div>
    </div>
  );
}

export default CreditBalanceEditModal;
