import React, { useState, useEffect, useRef, useCallback } from 'react';
import { useClient } from '../context/ClientContext';
import { useAuth } from '../context/AuthContext';
import { updateCreditHistoryEntry } from '../api/hoaDuesService';
import { translateToSpanish } from '../api/translate';
import { isSuperAdmin, isAdmin } from '../utils/userRoles';
import { getMexicoDateString, dateOnlyInputToMexicoISO } from '../utils/timezone';
import { useDesktopStrings } from '../hooks/useDesktopStrings';
import {
  getAutogeneratedUserMessage,
  getAutogeneratedUserMessageEs,
  resolveCreditUserMessage,
  resolveCreditUserMessageEs
} from '@shared/utils/creditUserMessage.js';
import { ALLOWED_CREDIT_SOURCES } from '@shared/utils/creditSources.js';
import { handleDecimalAmountChange, parseDecimalInput } from '../utils/decimalAmountInput.js';
import '../styles/SandylandModalTheme.css';
import '../styles/CreditBalanceModals.css';

function inferCreditEntryType(amountValue) {
  return amountValue >= 0 ? 'credit_added' : 'credit_used';
}

function CreditBalanceEditEntryModal({ isOpen, onClose, unitId, entry, onUpdate }) {
  const { selectedClient } = useClient();
  const { samsUser } = useAuth();
  const { t } = useDesktopStrings();
  
  const [entryDate, setEntryDate] = useState('');
  const [amount, setAmount] = useState('');
  const [notes, setNotes] = useState('');
  const [userMessage, setUserMessage] = useState('');
  const [userMessageEs, setUserMessageEs] = useState('');
  const [source, setSource] = useState('');
  const [loading, setLoading] = useState(false);
  const [isTranslating, setIsTranslating] = useState(false);
  const [error, setError] = useState(null);
  const userMessageTouchedRef = useRef(false);
  const userMessageEsTouchedRef = useRef(false);

  const canEdit = isSuperAdmin(samsUser) || isAdmin(samsUser, selectedClient?.id);

  useEffect(() => {
    if (isOpen && entry) {
      let dateStr = '';
      if (entry.timestamp) {
        if (entry.timestamp.raw && typeof entry.timestamp.raw === 'string') {
          const date = new Date(entry.timestamp.raw);
          dateStr = date.toISOString().split('T')[0];
        } else if (typeof entry.timestamp === 'string') {
          const date = new Date(entry.timestamp);
          dateStr = date.toISOString().split('T')[0];
        }
      }
      
      const amountValue = entry.amount || 0;
      const entrySource = entry.source || 'admin';
      const entryType = entry.type || inferCreditEntryType(amountValue);
      const entryContext = {
        userMessage: entry.userMessage,
        userMessage_es: entry.userMessage_es,
        notes: entry.notes || '',
        source: entrySource,
        type: entryType
      };
      const resolvedUserMessage = resolveCreditUserMessage(entryContext);
      const resolvedUserMessageEs = resolveCreditUserMessageEs(entryContext);

      setEntryDate(dateStr || getMexicoDateString().split('T')[0]);
      setAmount(amountValue.toString());
      setNotes(entry.notes || '');
      setUserMessage(resolvedUserMessage);
      setUserMessageEs(resolvedUserMessageEs);
      setSource(entrySource);
      userMessageTouchedRef.current = false;
      userMessageEsTouchedRef.current = false;
      setError(null);
    }
  }, [isOpen, entry]);

  const amountValue = parseDecimalInput(amount) || 0;
  const entryType = inferCreditEntryType(amountValue);

  const applyDefaultUserMessage = (nextSource, nextAmount) => {
    if (userMessageTouchedRef.current && userMessageEsTouchedRef.current) {
      return;
    }
    const nextType = inferCreditEntryType(parseDecimalInput(nextAmount) || 0);
    if (!userMessageTouchedRef.current) {
      setUserMessage(getAutogeneratedUserMessage({ source: nextSource, type: nextType }));
    }
    if (!userMessageEsTouchedRef.current) {
      setUserMessageEs(getAutogeneratedUserMessageEs({ source: nextSource, type: nextType }));
    }
  };

  const handleTranslate = useCallback(async () => {
    if (!userMessage.trim()) {
      return;
    }
    setIsTranslating(true);
    try {
      if (!userMessageEs.trim()) {
        const result = await translateToSpanish(userMessage.trim());
        if (result.success) {
          userMessageEsTouchedRef.current = true;
          setUserMessageEs(result.translatedText);
        }
      }
    } finally {
      setIsTranslating(false);
    }
  }, [userMessage, userMessageEs]);

  const handleSave = async () => {
    if (!canEdit) {
      setError(t('creditEntry.errorNoPermission'));
      return;
    }

    const parsedAmount = parseDecimalInput(amount);
    if (isNaN(parsedAmount)) {
      setError(t('creditEntry.errorValidAmount'));
      return;
    }

    if (!notes.trim()) {
      setError(t('creditEntry.errorProvideNotes'));
      return;
    }

    if (!userMessage.trim()) {
      setError(t('creditEdit.errorUserMessage'));
      return;
    }

    if (!entryDate) {
      setError(t('creditEntry.errorProvideDate'));
      return;
    }

    if (!source.trim()) {
      setError(t('creditEntry.errorProvideSource'));
      return;
    }

    setLoading(true);
    setError(null);

    try {
      const dateISO = dateOnlyInputToMexicoISO(entryDate);
      
      await updateCreditHistoryEntry(
        selectedClient.id,
        unitId,
        entry.id,
        {
          date: dateISO,
          amount: parsedAmount,
          notes: notes.trim(),
          source: source.trim(),
          userMessage: userMessage.trim(),
          userMessage_es: userMessageEs.trim()
        }
      );

      if (onUpdate) {
        await onUpdate();
      }

      onClose();
    } catch (err) {
      console.error('Error updating credit history entry:', err);
      setError(err.message || t('creditEntry.errorUpdateFailed'));
    } finally {
      setLoading(false);
    }
  };

  const handleCancel = () => {
    setEntryDate('');
    setAmount('');
    setNotes('');
    setUserMessage('');
    setUserMessageEs('');
    setSource('');
    userMessageTouchedRef.current = false;
    userMessageEsTouchedRef.current = false;
    setError(null);
    onClose();
  };

  if (!isOpen || !entry) {
    return null;
  }

  if (!canEdit) {
    return (
      <div className="sandyland-modal-overlay" onClick={onClose}>
        <div className="sandyland-modal credit-balance-modal" onClick={(e) => e.stopPropagation()}>
          <div className="sandyland-modal-header credit-balance-modal-header">
            <h2 className="sandyland-modal-title credit-balance-modal-title">{t('creditEdit.accessDenied')}</h2>
            <button type="button" className="credit-modal-close" onClick={onClose} aria-label={t('creditHistory.close')}>×</button>
          </div>
          <div className="sandyland-modal-content credit-balance-modal-content">
            <p>{t('creditEntry.errorNoPermission')}</p>
            <p>{t('creditEntry.errorAdminOnly')}</p>
          </div>
          <div className="sandyland-modal-buttons">
            <button type="button" className="sandyland-btn sandyland-btn-secondary" onClick={onClose}>
              {t('creditHistory.close')}
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="sandyland-modal-overlay" onClick={handleCancel}>
      <div className="sandyland-modal credit-balance-modal" onClick={(e) => e.stopPropagation()}>
        <div className="sandyland-modal-header credit-balance-modal-header">
          <h2 className="sandyland-modal-title credit-balance-modal-title">{t('creditEntry.title', { unitId })}</h2>
          <button type="button" className="credit-modal-close" onClick={handleCancel} aria-label={t('creditEdit.cancel')}>×</button>
        </div>
        
        <div className="sandyland-modal-content credit-balance-modal-content">
          {error && (
            <div className="credit-balance-error" role="alert">
              {error}
            </div>
          )}
          
          <div className="credit-balance-form-group">
            <label htmlFor="entryDate">{t('creditEdit.entryDateRequired')}</label>
            <input
              type="date"
              id="entryDate"
              value={entryDate}
              onChange={(e) => setEntryDate(e.target.value)}
              disabled={loading}
              required
            />
            <div className="credit-balance-form-hint">
              {t('creditEdit.entryDateHint')}
            </div>
          </div>

          <div className="credit-balance-form-group">
            <label htmlFor="amount">{t('creditEntry.amountRequired')}</label>
            <input
              type="text"
              inputMode="decimal"
              id="amount"
              className="credit-balance-amount-input"
              value={amount}
              onChange={(e) => {
                const accepted = handleDecimalAmountChange(e, setAmount, { allowNegative: true });
                if (accepted !== null) {
                  applyDefaultUserMessage(source, accepted);
                }
              }}
              placeholder={t('creditEntry.amountPlaceholder')}
              disabled={loading}
              required
              autoComplete="off"
            />
            <div className="credit-balance-form-hint">
              {t('creditEntry.amountHint')}
            </div>
          </div>

          <div className="credit-balance-field-pair">
            <div className="credit-balance-form-group">
              <label htmlFor="notes">{t('creditEdit.notesRequired')}</label>
              <textarea
                id="notes"
                value={notes}
                onChange={(e) => setNotes(e.target.value)}
                placeholder={t('creditEntry.notesPlaceholder')}
                rows="3"
                disabled={loading}
                required
              />
              <div className="credit-balance-form-hint">
                {t('creditEdit.notesAuditHint')}
              </div>
            </div>

            <div className="credit-balance-form-group">
              <label htmlFor="userMessage">{t('creditEdit.userMessageRequired')}</label>
              <textarea
                id="userMessage"
                value={userMessage}
                onChange={(e) => {
                  userMessageTouchedRef.current = true;
                  setUserMessage(e.target.value);
                }}
                placeholder={t('creditEdit.userMessagePlaceholder')}
                rows="2"
                disabled={loading}
                required
              />
              <div className="credit-balance-form-hint">
                {t('creditEdit.userMessageHint')}
              </div>
            </div>
          </div>

          <div className="credit-balance-form-group">
            <label htmlFor="userMessageEs">{t('creditEdit.userMessageEsLabel')}</label>
            <textarea
              id="userMessageEs"
              value={userMessageEs}
              onChange={(e) => {
                userMessageEsTouchedRef.current = true;
                setUserMessageEs(e.target.value);
              }}
              placeholder={t('creditEdit.userMessageEsPlaceholder')}
              rows="2"
              disabled={loading}
            />
            <div className="credit-balance-form-hint">
              {t('creditEdit.userMessageEsHint')}
            </div>
          </div>

          <div className="credit-balance-form-group">
            <button
              type="button"
              className="sandyland-btn sandyland-btn-secondary"
              onClick={handleTranslate}
              disabled={loading || isTranslating || !userMessage.trim()}
            >
              {isTranslating ? t('creditEdit.translating') : t('creditEdit.translateToSpanish')}
            </button>
          </div>

          <div className="credit-balance-form-group">
            <label htmlFor="source">{t('creditEntry.sourceRequired')}</label>
            <select
              id="source"
              value={source}
              onChange={(e) => {
                setSource(e.target.value);
                applyDefaultUserMessage(e.target.value, amount);
              }}
              disabled={loading}
              required
            >
              {ALLOWED_CREDIT_SOURCES.map((src) => (
                <option key={src} value={src}>{src}</option>
              ))}
            </select>
          </div>

          <div className="credit-balance-form-note">
            <strong>{t('creditEdit.noteTitle')}</strong> {t('creditEntry.noteBody')}
          </div>
        </div>

        <div className="sandyland-modal-buttons">
          <button 
            type="button"
            className="sandyland-btn sandyland-btn-secondary" 
            onClick={handleCancel}
            disabled={loading}
          >
            {t('creditEdit.cancel')}
          </button>
          <button 
            type="button"
            className="sandyland-btn sandyland-btn-primary" 
            onClick={handleSave}
            disabled={loading || !entryDate || !amount || !notes.trim() || !userMessage.trim() || !source.trim()}
          >
            {loading ? t('creditEdit.saving') : t('creditEdit.saveChanges')}
          </button>
        </div>
      </div>
    </div>
  );
}

export default CreditBalanceEditEntryModal;
