import React, { useState, useEffect, useRef } from 'react';
import { useClient } from '../context/ClientContext';
import { useAuth } from '../context/AuthContext';
import { updateCreditHistoryEntry } from '../api/hoaDuesService';
import { isSuperAdmin, isAdmin } from '../utils/userRoles';
import { getMexicoDateString } from '../utils/timezone';
import { useDesktopStrings } from '../hooks/useDesktopStrings';
import {
  getAutogeneratedUserMessage,
  resolveCreditUserMessage
} from '@shared/utils/creditUserMessage.js';
import './CreditBalanceEditEntryModal.css';

function inferCreditEntryType(amountValue) {
  return amountValue >= 0 ? 'credit_added' : 'credit_used';
}

function CreditBalanceEditEntryModal({ isOpen, onClose, unitId, entry, onUpdate }) {
  const { selectedClient } = useClient();
  const { samsUser } = useAuth();
  const { t } = useDesktopStrings();
  
  const [entryDate, setEntryDate] = useState('');
  const [amount, setAmount] = useState('');
  const [notes, setNotes] = useState('');
  const [userMessage, setUserMessage] = useState('');
  const [source, setSource] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const userMessageTouchedRef = useRef(false);

  const canEdit = isSuperAdmin(samsUser) || isAdmin(samsUser, selectedClient?.id);

  useEffect(() => {
    if (isOpen && entry) {
      let dateStr = '';
      if (entry.timestamp) {
        if (entry.timestamp.raw && typeof entry.timestamp.raw === 'string') {
          const date = new Date(entry.timestamp.raw);
          dateStr = date.toISOString().split('T')[0];
        } else if (typeof entry.timestamp === 'string') {
          const date = new Date(entry.timestamp);
          dateStr = date.toISOString().split('T')[0];
        }
      }
      
      const amountValue = entry.amount || 0;
      const entrySource = entry.source || 'admin';
      const entryType = entry.type || inferCreditEntryType(amountValue);
      const resolvedUserMessage = resolveCreditUserMessage({
        userMessage: entry.userMessage,
        notes: entry.notes || '',
        source: entrySource,
        type: entryType
      });

      setEntryDate(dateStr || getMexicoDateString().split('T')[0]);
      setAmount(amountValue.toString());
      setNotes(entry.notes || '');
      setUserMessage(resolvedUserMessage);
      setSource(entrySource);
      userMessageTouchedRef.current = false;
      setError(null);
    }
  }, [isOpen, entry]);

  const amountValue = parseFloat(amount) || 0;
  const entryType = inferCreditEntryType(amountValue);

  const applyDefaultUserMessage = (nextSource, nextAmount) => {
    if (userMessageTouchedRef.current) {
      return;
    }
    setUserMessage(getAutogeneratedUserMessage({
      source: nextSource,
      type: inferCreditEntryType(parseFloat(nextAmount) || 0)
    }));
  };

  const handleSave = async () => {
    if (!canEdit) {
      setError(t('creditEntry.errorNoPermission'));
      return;
    }

    const parsedAmount = parseFloat(amount);
    if (isNaN(parsedAmount)) {
      setError(t('creditEntry.errorValidAmount'));
      return;
    }

    if (!notes.trim()) {
      setError(t('creditEntry.errorProvideNotes'));
      return;
    }

    if (!userMessage.trim()) {
      setError(t('creditEdit.errorUserMessage'));
      return;
    }

    if (!entryDate) {
      setError(t('creditEntry.errorProvideDate'));
      return;
    }

    if (!source.trim()) {
      setError(t('creditEntry.errorProvideSource'));
      return;
    }

    setLoading(true);
    setError(null);

    try {
      const dateISO = new Date(entryDate).toISOString();
      
      await updateCreditHistoryEntry(
        selectedClient.id,
        unitId,
        entry.id,
        {
          date: dateISO,
          amount: parsedAmount,
          notes: notes.trim(),
          source: source.trim(),
          userMessage: userMessage.trim()
        }
      );

      if (onUpdate) {
        await onUpdate();
      }

      onClose();
    } catch (err) {
      console.error('Error updating credit history entry:', err);
      setError(err.message || t('creditEntry.errorUpdateFailed'));
    } finally {
      setLoading(false);
    }
  };

  const handleCancel = () => {
    setEntryDate('');
    setAmount('');
    setNotes('');
    setUserMessage('');
    setSource('');
    userMessageTouchedRef.current = false;
    setError(null);
    onClose();
  };

  if (!isOpen || !entry) {
    return null;
  }

  if (!canEdit) {
    return (
      <div className="modal-backdrop">
        <div className="credit-balance-edit-entry-modal">
          <div className="modal-header">
            <h3>{t('creditEdit.accessDenied')}</h3>
            <button className="close-button" onClick={onClose}>×</button>
          </div>
          <div className="modal-body">
            <p>{t('creditEntry.errorNoPermission')}</p>
            <p>{t('creditEntry.errorAdminOnly')}</p>
          </div>
          <div className="modal-footer">
            <button className="btn-secondary" onClick={onClose}>
              {t('creditHistory.close')}
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="modal-backdrop">
      <div className="credit-balance-edit-entry-modal">
        <div className="modal-header">
          <h3>{t('creditEntry.title', { unitId })}</h3>
          <button className="close-button" onClick={handleCancel}>×</button>
        </div>
        
        <div className="modal-body">
          {error && (
            <div className="error-message">
              {error}
            </div>
          )}
          
          <div className="form-group">
            <label htmlFor="entryDate">{t('creditEdit.entryDateRequired')}</label>
            <input
              type="date"
              id="entryDate"
              value={entryDate}
              onChange={(e) => setEntryDate(e.target.value)}
              disabled={loading}
              required
            />
            <div className="form-hint">
              {t('creditEdit.entryDateHint')}
            </div>
          </div>

          <div className="form-group">
            <label htmlFor="amount">{t('creditEntry.amountRequired')}</label>
            <input
              type="number"
              id="amount"
              value={amount}
              onChange={(e) => {
                setAmount(e.target.value);
                applyDefaultUserMessage(source, e.target.value);
              }}
              placeholder={t('creditEntry.amountPlaceholder')}
              step="0.01"
              disabled={loading}
              required
            />
            <div className="form-hint">
              {t('creditEntry.amountHint')}
            </div>
          </div>

          <div className="form-group">
            <label htmlFor="notes">{t('creditEdit.notesRequired')}</label>
            <textarea
              id="notes"
              value={notes}
              onChange={(e) => setNotes(e.target.value)}
              placeholder={t('creditEntry.notesPlaceholder')}
              rows="3"
              disabled={loading}
              required
            />
            <div className="form-hint">
              {t('creditEdit.notesAuditHint')}
            </div>
          </div>

          <div className="form-group">
            <label htmlFor="userMessage">{t('creditEdit.userMessageRequired')}</label>
            <textarea
              id="userMessage"
              value={userMessage}
              onChange={(e) => {
                userMessageTouchedRef.current = true;
                setUserMessage(e.target.value);
              }}
              placeholder={t('creditEdit.userMessagePlaceholder')}
              rows="2"
              disabled={loading}
              required
            />
            <div className="form-hint">
              {t('creditEdit.userMessageHint')}
            </div>
          </div>

          <div className="form-group">
            <label htmlFor="source">{t('creditEntry.sourceRequired')}</label>
            <select
              id="source"
              value={source}
              onChange={(e) => {
                setSource(e.target.value);
                applyDefaultUserMessage(e.target.value, amount);
              }}
              disabled={loading}
              required
            >
              <option value="admin">admin</option>
              <option value="correction">correction</option>
              <option value="reconciliation">reconciliation</option>
              <option value="running_balance_computation">running_balance_computation</option>
              <option value="unifiedPayment">unifiedPayment</option>
              <option value="hoaDues">hoaDues</option>
              <option value="waterBills">waterBills</option>
            </select>
          </div>

          <div className="form-note">
            <strong>{t('creditEdit.noteTitle')}</strong> {t('creditEntry.noteBody')}
          </div>
        </div>

        <div className="modal-footer">
          <button 
            className="btn-secondary" 
            onClick={handleCancel}
            disabled={loading}
          >
            {t('creditEdit.cancel')}
          </button>
          <button 
            className="btn-primary" 
            onClick={handleSave}
            disabled={loading || !entryDate || !amount || !notes.trim() || !userMessage.trim() || !source.trim()}
          >
            {loading ? t('creditEdit.saving') : t('creditEdit.saveChanges')}
          </button>
        </div>
      </div>
    </div>
  );
}

export default CreditBalanceEditEntryModal;
