/**
 * Deterministic client-facing messages for credit history entries.
 *
 * Write path: computeUserMessageForWrite() persists userMessage alongside audit notes.
 * Read path: resolveCreditUserMessage() supplies userMessage for legacy entries lacking it.
 *
 * @module shared/utils/creditUserMessage
 */

/** Patterns that indicate internal/audit phrasing unsuitable for owner-facing statements. */
const INTERNAL_NOTE_PATTERNS = [
  /\|\s*Amount:/i,
  /\|\s*New Balance:/i,
  /\|\s*Source:/i,
  /\|\s*Transaction:/i,
  /centavos/i,
  /\bPAY-[A-Z0-9-]+\b/i,
  /\(overpayment/i,
  /repair \+\$/i,
  /credit used \$/i,
  /\bTXN[-:]/i
];

/** Maximum length for notes considered concise enough for direct client display. */
const USER_FRIENDLY_MAX_LENGTH = 100;

/**
 * Rule-based source/type → client-facing message (English-only; no localized write path on credit history).
 * Pure function of source and type — same inputs always yield the same output.
 */
const SOURCE_TYPE_MESSAGES = Object.freeze({
  unifiedPayment: {
    credit_added: 'Credit added from overpayment',
    credit_used: 'Credit applied to payment',
    payment: 'Credit applied to payment',
    adjustment: 'Credit adjustment'
  },
  hoaDues: {
    credit_added: 'Credit added from HOA dues payment',
    credit_used: 'Credit applied to HOA dues',
    payment: 'Credit applied to HOA dues',
    adjustment: 'Credit adjustment'
  },
  waterBills: {
    credit_added: 'Credit added from water bill payment',
    credit_used: 'Credit applied to water bills',
    payment: 'Credit applied to water bills',
    adjustment: 'Credit adjustment'
  },
  admin: {
    credit_added: 'Credit adjustment',
    credit_used: 'Credit adjustment',
    adjustment: 'Credit adjustment'
  },
  reconciliation: {
    credit_added: 'Reconciliation credit added',
    credit_used: 'Reconciliation credit applied',
    adjustment: 'Reconciliation adjustment'
  },
  correction: {
    credit_added: 'Credit correction',
    credit_used: 'Credit correction',
    adjustment: 'Credit correction'
  },
  running_balance_computation: {
    credit_added: 'Balance reconciliation',
    credit_used: 'Balance reconciliation',
    adjustment: 'Balance reconciliation'
  },
  year_end_rollover: {
    credit_added: 'Year-end credit rollover',
    credit_used: 'Year-end credit applied',
    adjustment: 'Year-end credit adjustment'
  },
  import: {
    credit_added: 'Imported credit entry',
    credit_used: 'Imported credit entry',
    adjustment: 'Imported credit entry'
  },
  imported: {
    credit_added: 'Imported credit entry',
    credit_used: 'Imported credit entry',
    adjustment: 'Imported credit entry'
  }
});

const DEFAULT_TYPE_MESSAGES = Object.freeze({
  credit_added: 'Credit added to account',
  credit_used: 'Credit applied to charges',
  payment: 'Credit applied to charges',
  adjustment: 'Credit adjustment',
  starting_balance: 'Opening credit balance'
});

/**
 * @param {string} [notes]
 * @returns {boolean}
 */
export function isNotesUserFriendly(notes) {
  if (!notes || typeof notes !== 'string') {
    return false;
  }

  const trimmed = notes.trim();
  if (!trimmed || trimmed.length > USER_FRIENDLY_MAX_LENGTH) {
    return false;
  }

  return !INTERNAL_NOTE_PATTERNS.some((pattern) => pattern.test(trimmed));
}

/**
 * Deterministic mapping from source/type to a stable client-facing message.
 *
 * @param {{ source?: string, type?: string }} params
 * @returns {string}
 */
export function getAutogeneratedUserMessage({ source, type }) {
  const normalizedSource = String(source || '').trim();
  const normalizedType = String(type || 'adjustment').trim();

  const sourceMessages = SOURCE_TYPE_MESSAGES[normalizedSource];
  if (sourceMessages) {
    return sourceMessages[normalizedType]
      || sourceMessages.adjustment
      || DEFAULT_TYPE_MESSAGES[normalizedType]
      || DEFAULT_TYPE_MESSAGES.adjustment;
  }

  return DEFAULT_TYPE_MESSAGES[normalizedType] || DEFAULT_TYPE_MESSAGES.adjustment;
}

/**
 * Compute userMessage at write time (persisted on the entry).
 *
 * @param {{ notes?: string, source?: string, type?: string }} params
 * @returns {string}
 */
export function computeUserMessageForWrite({ notes, source, type }) {
  if (isNotesUserFriendly(notes)) {
    return notes.trim();
  }

  return getAutogeneratedUserMessage({ source, type });
}

/**
 * Resolve client-facing message for statement/read surfaces.
 * Uses persisted userMessage when present; otherwise falls back per contract rules.
 *
 * @param {{ userMessage?: string, notes?: string, source?: string, type?: string }} entry
 * @returns {string}
 */
export function resolveCreditUserMessage({ userMessage, notes, source, type }) {
  if (userMessage && typeof userMessage === 'string' && userMessage.trim()) {
    return userMessage.trim();
  }

  if (isNotesUserFriendly(notes)) {
    return notes.trim();
  }

  return getAutogeneratedUserMessage({ source, type });
}
