// Mobile-specific version utilities
// Imports version.json which is auto-generated by updateVersion.js at build time

// Import version data from auto-generated version.json
import versionData from '../../version.json';

// Environment-specific config
const environmentConfigs = {
  development: {
    icon: '🔧',
    color: '#2196F3',
    label: 'Development'
  },
  staging: {
    icon: '🧪',
    color: '#FF9800',
    label: 'Staging'
  },
  production: {
    icon: '🚀',
    color: '#4CAF50',
    label: 'Production'
  }
};

export const getVersionInfo = () => {
  const env = versionData.environment || import.meta.env.MODE || 'development';
  const envConfig = environmentConfigs[env] || environmentConfigs.development;
  
  // Format build date nicely
  let buildDateFormatted = 'Unknown';
  try {
    if (versionData.buildDate) {
      buildDateFormatted = new Date(versionData.buildDate).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      });
    }
  } catch (e) {
    console.warn('Could not format build date:', e);
  }
  
  return {
    // Basic version info (from version.json)
    version: versionData.version || '0.0.0',
    versionDisplay: `v${versionData.version || '0.0.0'}`,
    buildDate: versionData.buildDate,
    buildDateFormatted,
    buildNumber: versionData.build?.buildNumber || versionData.buildTimestamp?.toString() || '',
    
    // Environment info
    environment: env,
    displayEnvironment: envConfig.label,
    environmentConfig: envConfig,
    
    // App identity (from version.json)
    appName: versionData.appName || 'SAMS Mobile',
    shortName: versionData.shortName || 'SAMS',
    fullName: 'Sandyland Asset Management System',
    description: 'Mobile property management for HOA communities',
    
    // Company info (from version.json)
    companyName: versionData.companyName || 'Sandyland Property Management',
    copyright: versionData.copyright || new Date().getFullYear(),
    developers: versionData.developers || ['Michael Landesman', 'Claude AI'],
    
    // Features list (from version.json)
    features: versionData.features || [
      'PWA Support',
      'Multi-Client Management',
      'Financial Reporting',
      'Document Storage',
      'Unit Management'
    ],
    
    // Git info (from version.json)
    gitBranch: versionData.git?.branch || versionData.gitBranch || 'main',
    gitCommit: versionData.git?.hash || versionData.gitCommit || 'unknown',
    gitDate: versionData.git?.lastCommitDate || null,
    
    // Build info
    build: versionData.build || {},
    deployment: versionData.deployment || {},
    releaseNotes: versionData.releaseNotes || {}
  };
};

export const getEnvironmentStyles = () => {
  const env = versionData.environment || import.meta.env.MODE || 'development';
  
  const styles = {
    development: {
      backgroundColor: '#2196F3',
      color: '#ffffff'
    },
    staging: {
      backgroundColor: '#FF9800',
      color: '#ffffff'
    },
    production: {
      backgroundColor: '#4CAF50',
      color: '#ffffff'
    }
  };
  
  return styles[env] || styles.development;
};

// Export version for quick access (from version.json)
export const VERSION = versionData.version || '0.0.0';

// Export raw version data for advanced use
export const rawVersionData = versionData;
