/**
 * Unit tests for credit userMessage contract (Issue #337)
 */

import {
  isNotesUserFriendly,
  getAutogeneratedUserMessage,
  computeUserMessageForWrite,
  resolveCreditUserMessage
} from '../creditUserMessage.js';
import { createCreditHistoryEntry } from '../creditBalanceUtils.js';

describe('creditUserMessage contract', () => {
  describe('isNotesUserFriendly', () => {
    test('accepts concise owner-facing notes', () => {
      expect(isNotesUserFriendly('Credit added from owner payment')).toBe(true);
      expect(isNotesUserFriendly('Overpayment of $50.00 added to credit')).toBe(true);
    });

    test('rejects internal audit phrasing', () => {
      const internalNote = 'HOA dues payment PAY-101-20250717-25 (overpayment +$50.00, credit used $20.00)';
      expect(isNotesUserFriendly(internalNote)).toBe(false);
      expect(isNotesUserFriendly('Adjustment | Amount: $100.00 | Source: admin')).toBe(false);
    });

    test('rejects long notes', () => {
      expect(isNotesUserFriendly('x'.repeat(101))).toBe(false);
    });
  });

  describe('getAutogeneratedUserMessage', () => {
    test('returns deterministic message for source/type pairs', () => {
      const first = getAutogeneratedUserMessage({ source: 'hoaDues', type: 'credit_added' });
      const second = getAutogeneratedUserMessage({ source: 'hoaDues', type: 'credit_added' });
      expect(first).toBe('Credit added from HOA dues payment');
      expect(second).toBe(first);
    });

    test('covers reconciliation source', () => {
      expect(getAutogeneratedUserMessage({ source: 'reconciliation', type: 'credit_added' }))
        .toBe('Reconciliation credit added');
    });
  });

  describe('computeUserMessageForWrite', () => {
    test('mirrors user-friendly notes', () => {
      const notes = 'Owner goodwill credit for landscaping';
      expect(computeUserMessageForWrite({ notes, source: 'admin', type: 'credit_added' }))
        .toBe(notes);
    });

    test('generates mapping for internal notes', () => {
      const notes = 'HOA dues payment PAY-101-20250717-25 (overpayment +$50.00)';
      expect(computeUserMessageForWrite({ notes, source: 'hoaDues', type: 'credit_added' }))
        .toBe('Credit added from HOA dues payment');
    });
  });

  describe('resolveCreditUserMessage (read-side legacy fallback)', () => {
    test('uses persisted userMessage when present', () => {
      expect(resolveCreditUserMessage({
        userMessage: 'Stored client message',
        notes: 'Internal audit note with PAY-123',
        source: 'hoaDues',
        type: 'credit_added'
      })).toBe('Stored client message');
    });

    test('falls back to friendly notes for legacy entries', () => {
      const notes = 'Manual credit for painting reimbursement';
      expect(resolveCreditUserMessage({
        notes,
        source: 'admin',
        type: 'credit_added'
      })).toBe(notes);
    });

    test('derives mapping for legacy internal notes', () => {
      expect(resolveCreditUserMessage({
        notes: 'HOA dues payment PAY-101-20250717-25 (overpayment +$50.00)',
        source: 'hoaDues',
        type: 'credit_used'
      })).toBe('Credit applied to HOA dues');
    });
  });

  describe('createCreditHistoryEntry write path', () => {
    test('persists notes and userMessage for autogenerated unified payment entry', () => {
      const entry = createCreditHistoryEntry({
        amount: 5000,
        transactionId: 'txn-1',
        notes: 'Overpayment of $50.00 added to credit',
        type: 'credit_added',
        source: 'unifiedPayment'
      });

      expect(entry.notes).toBe('Overpayment of $50.00 added to credit');
      expect(entry.userMessage).toBe('Overpayment of $50.00 added to credit');
    });

    test('honors explicit userMessage override on write', () => {
      const entry = createCreditHistoryEntry({
        amount: 1000,
        transactionId: 'txn-3',
        notes: 'Internal audit note with PAY-999',
        type: 'credit_added',
        source: 'admin',
        userMessage: 'Custom owner message'
      });

      expect(entry.userMessage).toBe('Custom owner message');
      expect(entry.notes).toContain('PAY-999');
    });
  });

  describe('statement data preparation shape', () => {
    test('resolveCreditUserMessage produces client-safe field for legacy and new entries', () => {
      const legacyInternal = {
        notes: 'HOA dues payment PAY-101-20250717-25 (overpayment +$50.00)',
        source: 'hoaDues',
        type: 'credit_added'
      };
      const newEntry = {
        ...legacyInternal,
        userMessage: 'Credit added from HOA dues payment'
      };

      const legacyDisplay = resolveCreditUserMessage(legacyInternal);
      const newDisplay = resolveCreditUserMessage(newEntry);

      expect(legacyDisplay).toBe('Credit added from HOA dues payment');
      expect(newDisplay).toBe(legacyDisplay);
    });
  });
});
