/**
 * Unit tests for credit userMessage contract (Issue #337)
 */

import {
  isNotesUserFriendly,
  getAutogeneratedUserMessage,
  getAutogeneratedUserMessageEs,
  computeUserMessageForWrite,
  resolveCreditUserMessage,
  resolveCreditUserMessageEs,
  resolveCreditUserMessageForLocale,
  lookupSpanishForEnglishTemplate,
  getAllCreditUserMessageTemplates
} from '../creditUserMessage.js';
import { createCreditHistoryEntry } from '../creditBalanceUtils.js';

describe('creditUserMessage contract', () => {
  describe('isNotesUserFriendly', () => {
    test('accepts concise owner-facing notes', () => {
      expect(isNotesUserFriendly('Credit added from owner payment')).toBe(true);
      expect(isNotesUserFriendly('Overpayment of $50.00 added to credit')).toBe(true);
    });

    test('rejects internal audit phrasing', () => {
      const internalNote = 'HOA dues payment PAY-101-20250717-25 (overpayment +$50.00, credit used $20.00)';
      expect(isNotesUserFriendly(internalNote)).toBe(false);
      expect(isNotesUserFriendly('Adjustment | Amount: $100.00 | Source: admin')).toBe(false);
    });

    test('rejects long notes', () => {
      expect(isNotesUserFriendly('x'.repeat(101))).toBe(false);
    });
  });

  describe('getAutogeneratedUserMessage', () => {
    test('returns deterministic message for source/type pairs', () => {
      const first = getAutogeneratedUserMessage({ source: 'hoaDues', type: 'credit_added' });
      const second = getAutogeneratedUserMessage({ source: 'hoaDues', type: 'credit_added' });
      expect(first).toBe('Credit added from HOA dues payment');
      expect(second).toBe(first);
    });

    test('covers reconciliation source', () => {
      expect(getAutogeneratedUserMessage({ source: 'reconciliation', type: 'credit_added' }))
        .toBe('Reconciliation credit added');
    });
  });

  describe('bilingual templates', () => {
    test('getAutogeneratedUserMessageEs returns Spanish for known source/type', () => {
      expect(getAutogeneratedUserMessageEs({ source: 'hoaDues', type: 'credit_added' }))
        .toBe('Crédito agregado por pago de cuotas de mantenimiento');
    });

    test('lookupSpanishForEnglishTemplate maps EN templates', () => {
      expect(lookupSpanishForEnglishTemplate('Credit applied to HOA dues'))
        .toBe('Crédito aplicado a cuotas de mantenimiento');
      expect(lookupSpanishForEnglishTemplate('Unknown custom text')).toBeNull();
    });

    test('every EN template has a non-empty ES companion', () => {
      for (const template of getAllCreditUserMessageTemplates()) {
        expect(template.en).toBeTruthy();
        expect(template.es).toBeTruthy();
      }
    });
  });

  describe('computeUserMessageForWrite', () => {
    test('mirrors user-friendly notes in EN with empty ES when not mappable', () => {
      const notes = 'Owner goodwill credit for landscaping';
      expect(computeUserMessageForWrite({ notes, source: 'admin', type: 'credit_added' }))
        .toEqual({ userMessage: notes, userMessage_es: '' });
    });

    test('generates bilingual mapping for internal notes', () => {
      const notes = 'HOA dues payment PAY-101-20250717-25 (overpayment +$50.00)';
      expect(computeUserMessageForWrite({ notes, source: 'hoaDues', type: 'credit_added' }))
        .toEqual({
          userMessage: 'Credit added from HOA dues payment',
          userMessage_es: 'Crédito agregado por pago de cuotas de mantenimiento'
        });
    });

    test('honors explicit bilingual overrides independently', () => {
      expect(computeUserMessageForWrite({
        notes: 'internal',
        source: 'admin',
        type: 'credit_added',
        userMessage: 'Custom EN',
        userMessage_es: 'Custom ES'
      })).toEqual({ userMessage: 'Custom EN', userMessage_es: 'Custom ES' });
    });

    test('preserves explicitly empty userMessage_es without template fallback', () => {
      expect(computeUserMessageForWrite({
        notes: 'internal',
        source: 'admin',
        type: 'credit_added',
        userMessage: 'Custom EN',
        userMessage_es: ''
      })).toEqual({ userMessage: 'Custom EN', userMessage_es: '' });
    });

    test('explicit EN without ES uses template lookup not generic autogen', () => {
      expect(computeUserMessageForWrite({
        notes: 'internal',
        source: 'hoaDues',
        type: 'credit_added',
        userMessage: 'Credit added from HOA dues payment'
      })).toEqual({
        userMessage: 'Credit added from HOA dues payment',
        userMessage_es: 'Crédito agregado por pago de cuotas de mantenimiento'
      });
    });

    test('explicit custom EN without ES leaves ES empty', () => {
      expect(computeUserMessageForWrite({
        notes: 'internal',
        source: 'admin',
        type: 'credit_added',
        userMessage: 'Owner goodwill credit for landscaping'
      })).toEqual({
        userMessage: 'Owner goodwill credit for landscaping',
        userMessage_es: ''
      });
    });
  });

  describe('resolveCreditUserMessage (read-side legacy fallback)', () => {
    test('uses persisted userMessage when present', () => {
      expect(resolveCreditUserMessage({
        userMessage: 'Stored client message',
        notes: 'Internal audit note with PAY-123',
        source: 'hoaDues',
        type: 'credit_added'
      })).toBe('Stored client message');
    });

    test('falls back to friendly notes for legacy entries', () => {
      const notes = 'Manual credit for painting reimbursement';
      expect(resolveCreditUserMessage({
        notes,
        source: 'admin',
        type: 'credit_added'
      })).toBe(notes);
    });

    test('derives mapping for legacy internal notes', () => {
      expect(resolveCreditUserMessage({
        notes: 'HOA dues payment PAY-101-20250717-25 (overpayment +$50.00)',
        source: 'hoaDues',
        type: 'credit_used'
      })).toBe('Credit applied to HOA dues');
    });
  });

  describe('resolveCreditUserMessageEs', () => {
    test('uses persisted userMessage_es when present', () => {
      expect(resolveCreditUserMessageEs({
        userMessage: 'Credit adjustment',
        userMessage_es: 'Ajuste personalizado',
        source: 'admin',
        type: 'credit_added'
      })).toBe('Ajuste personalizado');
    });

    test('falls back to template mapping from resolved EN', () => {
      expect(resolveCreditUserMessageEs({
        userMessage: 'Credit applied to HOA dues',
        source: 'hoaDues',
        type: 'credit_used'
      })).toBe('Crédito aplicado a cuotas de mantenimiento');
    });

    test('returns empty for custom English without persisted ES', () => {
      expect(resolveCreditUserMessageEs({
        notes: 'Owner goodwill credit for landscaping',
        source: 'admin',
        type: 'credit_added'
      })).toBe('');
    });

    test('returns autogen ES only when resolved EN matches autogen template', () => {
      expect(resolveCreditUserMessageEs({
        source: 'hoaDues',
        type: 'credit_added'
      })).toBe('Crédito agregado por pago de cuotas de mantenimiento');
    });
  });

  describe('resolveCreditUserMessageForLocale', () => {
    test('picks Spanish persisted field for spanish language', () => {
      const entry = {
        userMessage: 'Credit adjustment',
        userMessage_es: 'Ajuste de crédito'
      };
      expect(resolveCreditUserMessageForLocale(entry, 'spanish')).toBe('Ajuste de crédito');
      expect(resolveCreditUserMessageForLocale(entry, 'english')).toBe('Credit adjustment');
    });
  });

  describe('createCreditHistoryEntry write path', () => {
    test('persists notes and userMessage for autogenerated unified payment entry', () => {
      const entry = createCreditHistoryEntry({
        amount: 5000,
        transactionId: 'txn-1',
        notes: 'Overpayment of $50.00 added to credit',
        type: 'credit_added',
        source: 'unifiedPayment'
      });

      expect(entry.notes).toBe('Overpayment of $50.00 added to credit');
      expect(entry.userMessage).toBe('Overpayment of $50.00 added to credit');
      expect(entry.userMessage_es).toBe('');
    });

    test('honors explicit userMessage override on write', () => {
      const entry = createCreditHistoryEntry({
        amount: 1000,
        transactionId: 'txn-3',
        notes: 'Internal audit note with PAY-999',
        type: 'credit_added',
        source: 'admin',
        userMessage: 'Custom owner message',
        userMessage_es: 'Mensaje personalizado'
      });

      expect(entry.userMessage).toBe('Custom owner message');
      expect(entry.userMessage_es).toBe('Mensaje personalizado');
      expect(entry.notes).toContain('PAY-999');
    });

    test('preserves explicitly empty userMessage_es on write', () => {
      const entry = createCreditHistoryEntry({
        amount: 1000,
        transactionId: 'txn-5',
        notes: 'Internal audit note',
        type: 'credit_added',
        source: 'admin',
        userMessage: 'Custom owner message',
        userMessage_es: ''
      });

      expect(entry.userMessage).toBe('Custom owner message');
      expect(entry.userMessage_es).toBe('');
    });

    test('persists bilingual autogenerated messages for internal notes', () => {
      const entry = createCreditHistoryEntry({
        amount: 1000,
        transactionId: 'txn-4',
        notes: 'HOA dues payment PAY-101-20250717-25 (overpayment +$50.00)',
        type: 'credit_added',
        source: 'hoaDues'
      });

      expect(entry.userMessage).toBe('Credit added from HOA dues payment');
      expect(entry.userMessage_es).toBe('Crédito agregado por pago de cuotas de mantenimiento');
    });
  });

  describe('statement data preparation shape', () => {
    test('resolveCreditUserMessage produces client-safe field for legacy and new entries', () => {
      const legacyInternal = {
        notes: 'HOA dues payment PAY-101-20250717-25 (overpayment +$50.00)',
        source: 'hoaDues',
        type: 'credit_added'
      };
      const newEntry = {
        ...legacyInternal,
        userMessage: 'Credit added from HOA dues payment'
      };

      const legacyDisplay = resolveCreditUserMessage(legacyInternal);
      const newDisplay = resolveCreditUserMessage(newEntry);

      expect(legacyDisplay).toBe('Credit added from HOA dues payment');
      expect(newDisplay).toBe(legacyDisplay);
    });
  });
});
